#Choosing the host for the task
- hosts: all
  #apply 'super user do' over the task
  become: yes 

  tasks:  
    
    - name: include secret
      include_vars: secret.yml
    
    - name: Make work directory.
      file:
        dest: /home/"{{ user }}"/docker-projects/samba/ 
        owner: "{{ user }}" 
        group: "{{ user }}"
        mode: "{{ access }}"
        state: directory    
    
    - name: Make folder to share files.
      file:
        dest: /home/scripthead/shared
        mode: "{{ access }}"
        owner: "{{ user }}" 
        group: "{{ user }}"
        state: directory
          
    - name: Copy folder the project.
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ user }}" 
        group: "{{ user }}"
        mode: "{{ access }}"
      with_items:
        - src: docker-compose.yaml #server samba
          dest: /home/scripthead/docker-projects/samba/
     
    - name: Deploy Docker Compose stack.
      docker_compose:
        project_src: /home/scripthead/docker-projects/samba/
        files:
          - docker-compose.yaml
